trigger:
- main

pool:
  name: Kevin_pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: 
    sudo apt-get update
    sudo apt-get install -y zip
  displayName: 'Install zip utility'
  
- script: |
    npm install
    npm run build
    cd build
    zip -r ../app.zip .
  displayName: 'npm install, build and zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'drop'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'MyAzureConnection'
    resourceGroupName: 'primeV2'
    appName: 'youtube-test-clone'
    package: '$(System.DefaultWorkingDirectory)/drop/app.zip'
    appType: 'webAppLinux'
    runtimeStack: 'NODE|20-lts'
    deploymentMethod: 'auto'
