trigger:
- main

pool:
  name: Kevin_pool

steps:
- script: |
    node -v
    npm -v
    npm install
    npm run build
  displayName: 'Build React'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -r build/* $(Build.ArtifactStagingDirectory)/
  displayName: 'Copy React Build to Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifact'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'website'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appType: 'webAppLinux'
    appName: 'Youtube-test-clone'
    package: '$(Pipeline.Workspace)/website'
  displayName: 'Deploy to Azure Web App'
