pool:
  name: Kevin_pool

variables:
  imageName: ytclone
  containerPort: 80
  hostPort: 8080
  containername: $(imageName)-container
  dockerfilePath: Dockerfile

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
    
  - task: Docker@2
    inputs:
      command: 'build'
      repository: $(imageName)
      Dockerfile: '**/Dockerfile'
      buildContext: .
      tags: |
        latest

  - script: |
      docker run --rm -d -p $(hostPort):$(containerPort) --name $(containername) $(imageName):latest
    displayName: 'Run Docker Container'



