# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Kevin_pool

steps:
- script: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt install nodejs -y
    node -v
    npm -v
    npm install
    npm run build
    sudo apt update
    sudo apt install zip -y

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Build Output to Artifact Staging Directory'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'website'
    downloadPath: '$(System.ArtifactsDirectory)'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
#    archiveType: 'zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
#    replaceExistingArchive: true
#  displayName: 'Archive Build Output'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appType: 'webAppLinux'
    appName: 'Youtube-test-clone'
    package: '$(System.ArtifactsDirectory)/website'
  displayName: 'Deploy to Azure Web App'