trigger:
- main

pool:
  name: Kevin_pool

variables:
  imageName: 'youtube-backend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies & build'

- script: echo "hello world !!"