trigger:
- main

pool:
  name: Kevin_pool

variables:
  imageName: 'youtube-backend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies & build'

- task: Docker@2
  inputs:
    containerRegistry: 'ytcloneregistry'  # This must be a DockerHub or ACR service connection
    repository: 'kevinchacko1/ytclone-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
  displayName: 'Build & Push Docker Image to Docker.io'

# ✅ Deploy Docker container to Azure Web App for Containers
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appName: 'youtube-test'
    containers: 'kevinchacko1/ytclone-test:latest'
