trigger:
- main

pool:
  name: Kevin_pool
stages: 
  - stage: 'build'
    jobs:
      - job: 'Installation'

        steps:
        - task: NodeTool@0 
          inputs:
            versionSource: spec
            versionSpec: '22.14.0'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
            npm test

        - script: |
            docker build -t ytclone .
            docker run --name clone -d -p 3000:3000 ytclone:latest
              
