trigger:
- main

pool:
  name: Kevin_pool

variables:
  imageName: 'youtube-backend'
stages:
- stage: 'Build'
  jobs:
  - job: 'CI'
    steps:
    - task: NodeTool@0
      displayName: 'Install-node.js'
      inputs:
        versionSource: 'spec'
        versionSpec: '22.x'
        checkLatest: true

  - job: 'CD'
    steps:
      - task: AzureWebApp@1
        displayName: 'Deploy to Azure'
        inputs:
          azureSubscription: 'Azure subscription 1(ebcefc3c-ab59-45b9-8fbe-b00c1a4f7265)'
          appType: 'webAppLinux'
          appName: 'youtube-test-clone'
          deployToSlotOrASE: true
          resourceGroupName: 'primeV2'
          slotName: 'production'
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'
          runtimeStack: 'NODE|22-lts'
