trigger:
- main

pool:
  name: Kevin_pool

steps:
- script: |
    node -v
    npm -v
    npm install
    npm run build
  displayName: 'Install Node.js and Build React App'

- script: |
    sudo apt update
    sudo apt install zip -y
  displayName: 'Install zip utility'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
    replaceExistingArchive: true
  displayName: 'Archive Build Output'

- script: unzip -l $(Build.ArtifactStagingDirectory)/build.zip
  displayName: 'List ZIP Contents'

- script: unzip $(Build.ArtifactStagingDirectory)/build.zip
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appType: 'webAppLinux'
    appName: 'Youtube-test-clone'
    package: '$(Build.ArtifactStagingDirectory)/build'
  displayName: 'Deploy to Azure Web App'
