trigger:
- main

pool:
  name: Kevin_pool

variables:
  imageName: 'youtube-backend'
stages:
- stage: 'Build'
  jobs:
  - job: 'CI'
    steps:
    
      - script: |
          npm install
          npm run build
          zip -r $(Build.ArtifactStagingDirectory)/app.zip .
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - job: 'CD'
    steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
      - task: AzureWebApp@1
        displayName: 'Deploy to Azure'
        inputs:
          azureSubscription: 'Azure subscription 1(ebcefc3c-ab59-45b9-8fbe-b00c1a4f7265)'
          appType: 'webAppLinux'
          appName: 'youtube-test-clone'
          deployToSlotOrASE: true
          resourceGroupName: 'primeV2'
          slotName: 'production'
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'
          runtimeStack: 'NODE|22-lts'
