trigger:
- main

pool:
  name: Kevin_pool

variables:
  imageName: 'youtube-backend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies & build'

# ✅ Publish the build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'  # Ensure this path is correct
    ArtifactName: 'node-backend'
    publishLocation: 'Container'

# ✅ Download the artifact before deployment
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'node-backend'
    downloadType: 'single'
    downloadPath: '$(Pipeline.Workspace)'

# ✅ Build Docker image and push to ACR
- task: Docker@2
  inputs:
    containerRegistry: 'ytcloneregistry'
    repository: 'kevinchacko1/ytclone-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
  displayName: 'Build & Push Docker Image to Docker.io'

# ✅ Deploy to App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'
    appName: 'youtube-test'
    package: '$(Build.ArtifactStagingDirectory)/node-backend'  # Ensure this is correct
    runtimeStack: 'NODE|20-lts'
    
- script: |
    echo "Checking build directory contents:"
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'Check build directory contents'

